project:
  type: website
  output-dir: docs

website:
  title: Herv√© Bredin
  navbar:
    right:
      # - consulting.qmd
      - about.qmd
      - blog.qmd
      # - collab.qmd
      - icon: github
        href: https://github.com/hbredin
      - icon: twitter
        href: https://twitter.com/hbredin
      - icon: linkedin
        href: https://www.linkedin.com/in/herve-bredin
  google-analytics: "G-2N1PYH6CZP"



